### ISSUE TITLE
Run Store + bundles in a worker?

### ISSUE THREAD

**Issue by developit** [HenrikJoreteg/redux-bundler#2]
The use of strings for selectors and actions in `connect()` would make for a really nicely optimized worker boundary, better than Stockroom has been able to pull off.
Any thoughts on how one might push redux and bundled actions into a worker?

**Comment by HenrikJoreteg** [comment]
I'll work on putting together an example app when I get a chance. This is actually how I started building the app I just shipped, but ended up backing it out because I was using Firebase and running it in a worker, while it seemed to work, isn't officially supported and plus, it just felt kinda risky to do something more experimental like this in an app that's handling real financial transactions. So I backed it out, but... it's certainly doable.

**Comment by HenrikJoreteg** [comment]
Still needs some cleanup, it's double diffing, but... nearly ready to share :)

![screen shot 2018-01-26 at 11 16 49 pm](https://user-images.githubusercontent.com/67925/35469720-61470ae8-02f0-11e8-943e-5bf2403db2bb.png)

**Comment by HenrikJoreteg** [comment]
Here's the code: https://github.com/HenrikJoreteg/redux-bundler-worker-example
Here's the deployed app: https://redux-bundler-worker.netlify.com/
